ciphers/urls.py
from django.urls import path

from . import views

app_name = 'ciphers'
urlpatterns = [
    #urls for caesar
    path('', views.index, name='index'),
    path('caesar/<int:caesar_id>/', views.caesar_show, name='caesar_show'),
    path('create/', views.create, name='create'),
    path('<int:caesar_id>/update/', views.update, name='update'),
    path('<int:caesar_id>/delete/', views.delete, name='delete'),
    #urls for atbash
    path('atbash/<int:atbash_id>/', views.atbash_show, name='atbash_show'),
    #urls for alphanumeric
    path('alphanumeric/<int:alphanumeric_id>/', views.alphanumeric_show, name='alphanumeric_show'),
]

will_cipher/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ciphers/', include('ciphers.urls')),
    path('admin/', admin.site.urls),
]

ciphers/models.py
from django.db import models
from django.forms import ModelForm
import re

alphabet = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
backwards_alphabet = ['Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']
special_chars = ['.',':',' ',"'",'!','?','',',']

def alphabet_grid():
    offset = 0
    grid = []
    while offset < 26:
        row = rotate(alphabet, offset)
        grid.append(row)
        offset += 1
    return grid

def rotate(list, offset):
    return list[offset:] + list[:offset]

class Caesar(models.Model):

    caesar_text = models.CharField(max_length=500)

    def __str__(self):
        return self.caesar_text

    def encode(self, offset):
        return self.new_message(-offset)

    def decode(self, offset):
        return self.new_message(offset)

    def new_message(self, offset):
        list = []
        new_alphabet = rotate(alphabet, offset)
        for letter in self.caesar_text:
            if letter not in alphabet:
                list.append(letter)
            else:
                letter_index = new_alphabet.index(letter)
                new_letter = alphabet[letter_index]
                list.append(new_letter)
            message = ''.join(list)
        return message


class CaesarsForm(ModelForm):
    class Meta:
        model = Caesar
        fields = ['caesar_text']

class Atbash(models.Model):

    atbash_text = models.CharField(max_length=500)

    def __str__(self):
        return self.atbash_text

    def decode(self):
        list = []
        for character in self.atbash_text:
            if character not in alphabet:
                list.append(character)
            else:
                character_index = backwards_alphabet.index(character)
                new_character = alphabet[character_index]
                list.append(new_character)
            message = ''.join(list)
        return message

    def encode(self):
        list = []
        for character in self.atbash_text:
            if character not in alphabet:
                list.append(character)
            else:
                character_index = alphabet.index(character)
                new_character = backwards_alphabet[character_index]
                list.append(new_character)
            message = ''.join(list)
        return message

class AthbashsForm(ModelForm):
    class Meta:
        model = Atbash
        fields = ['atbash_text']

class Alphanumeric(models.Model):

    alphanumeric_text = models.CharField(max_length=500)

    def __str__(self):
        return self.alphanumeric_text

    def decode(self):
        list = []
        character_split = re.split('(\W)', self.alphanumeric_text)
        while '-' in character_split: character_split.remove('-')
        for character in character_split:
            if character in special_chars:
                list.append(character)
            else:
                character = int(character)
                letter = alphabet[character - 1]
                list.append(letter)
            message = ''.join(list)
        return message

    def encode(self):
        list = []
        for character in self.alphanumeric_text:
            if character not in alphabet:
                if list[-1] not in alphabet and list[-1] != '-':
                    list.append(character)
                else:
                    list.pop()
                    list.append(character)
            else:
                number = str(alphabet.index(character) + 1)
                list.append(number)
                list.append('-')
            message = ''.join(list)
        return message

class AlphanumericsForm(ModelForm):
    class Meta:
        model = Alphanumeric
        fields = ['alphanumeric_text']

class Vigenere(models.Model):

    vigenere_text = models.CharField(max_length=500)

    def __str__(self):
        return self.vigenere_text

    def keyword_length(self, keyword):
        list = []
        for character in self.vigenere_text:
            if character in alphabet:
                list.append(character)
            keyword_length = len(list)
        return keyword_length

    def repeat_keyword(self, keyword):
        length = self.keyword_length(keyword)
        while len(keyword) < length:
            keyword += keyword
        keyword = keyword[:length]
        return keyword

    def insert_special_chars(self, keyword):
        count = 0
        keyword = list(keyword)
        while count < len(self.vigenere_text):
            character = list(self.vigenere_text)[count]
            if character not in alphabet:
                keyword.insert(count, character)
            count += 1
        return keyword

    def encode(self, keyword):
        message = []
        new_keyword = self.repeat_keyword(keyword)
        final_keyword = self.insert_special_chars(new_keyword)
        for keyword_char, vtext_char in zip(final_keyword, self.vigenere_text):
            if vtext_char not in alphabet:
                message.append(vtext_char)
            else:
                vtext_index = alphabet.index(vtext_char)
                keyword_index = alphabet.index(keyword_char)
                grid_row = alphabet_grid()[keyword_index]
                final_char = grid_row[vtext_index]
                message.append(final_char)
            final_message = ''.join(message)
        return final_message

    def decode(self, keyword):
        message = []
        new_keyword = self.repeat_keyword(keyword)
        final_keyword = self.insert_special_chars(new_keyword)
        for keyword_char, vtext_char in zip(final_keyword, self.vigenere_text):
            if vtext_char not in alphabet:
                message.append(vtext_char)
            else:
                keyword_index = alphabet.index(keyword_char)
                grid_row = alphabet_grid()[keyword_index]
                secret_index = grid_row.index(vtext_char)
                final_char = alphabet[secret_index]
                message.append(final_char)
            final_message = ''.join(message)
        return final_message

class VigeneresForm(ModelForm):
    class Meta:
        model = Vigenere
        fields = ['vigenere_text']

ciphers/views.py
from django.shortcuts import get_object_or_404, render, redirect

from django.http import HttpResponse
from django.template import loader
from django.views.generic.edit import CreateView
from .models import Caesar, Atbash, Alphanumeric, Vigenere, CaesarsForm


def index(request):
    caesars = Caesar.objects.all()
    atbashs = Atbash.objects.all()
    alphanumerics = Alphanumeric.objects.all()
    context = {'caesars': caesars, 'atbashs': atbashs, 'alphanumerics': alphanumerics}
    return render(request, 'ciphers/index.html', context)

def caesar_show(request, caesar_id):
    caesar = get_object_or_404(Caesar, pk=caesar_id)
    return render(request, 'ciphers/caesar_show.html', {'caesar': caesar})

def atbash_show(request, atbash_id):
    atbash = get_object_or_404(Atbash, pk=atbash_id)
    return render(request, 'ciphers/atbash_show.html', {'atbash': atbash})

def alphanumeric_show(request, alphanumeric_id):
    alphanumeric = get_object_or_404(Alphanumeric, pk=alphanumeric_id)
    return render(request, 'ciphers/alphanumeric_show.html', {'alphanumeric': alphanumeric})

def create(request, template_name='ciphers/caesar_form.html'):
    form = CaesarsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('ciphers:index')
    return render(request, template_name, {'form': form})

def update(request, caesar_id, template_name='ciphers/caesar_form.html'):
    caesar = get_object_or_404(Caesar, pk=caesar_id)
    form = CaesarsForm(request.POST or None, instance=caesar)
    if form.is_valid():
        form.save()
        return redirect('ciphers:index')
    return render(request, template_name, {'form': form})

def delete(request, caesar_id, template_name='ciphers/caesar_delete.html'):
    caesar = get_object_or_404(Caesar, pk=caesar_id)
    if request.method=='POST':
        caesar.delete()
        return redirect('ciphers:index')
    return render(request, template_name, {'caesar': caesar})

ciphers/templates/ciphers/alphanumeric_show.html
<h2>Alphanumeric Message</h2>
  {{ alphanumeric }}

  {# { alphanumeric.decode() } #}


<a href="{% url 'ciphers:update' alphanumeric.id %}">Update Alphanumeric</a><br><br>
<a href="{% url 'ciphers:delete' alphanumeric.id %}">Delete Alphanumeric</a><br><br>

<a href="{% url 'ciphers:index' %}">Back to list of Alphanumerics</a>

ciphers/templates/ciphers/atbash_show.html
<h2>Atbash Message</h2>
  {{ atbash }}

  {# { atbash.decode() } #}


<a href="{% url 'ciphers:update' atbash.id %}">Update Atbash</a><br><br>
<a href="{% url 'ciphers:delete' atbash.id %}">Delete Atbash</a><br><br>

<a href="{% url 'ciphers:index' %}">Back to list of Atbashs</a>

ciphers/templates/ciphers/caesar_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Caesar Cipher</title>
  </head>
  <body>
    <div class="container">
      <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ caesar }}" ?
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

ciphers/templates/ciphers/caesar_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Caesar Cipher</title>
  </head>
  <body>
    <h1>Cipher</h1>
    <div class="container">
      <form  method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

ciphers/templates/ciphers/caesar_show.html
<h2>Caesar Message</h2>
  {{ caesar }}

  {# { caesar.decode(3) } #}


<a href="{% url 'ciphers:update' caesar.id %}">Update Caesar</a><br><br>
<a href="{% url 'ciphers:delete' caesar.id %}">Delete Caesar</a><br><br>

<a href="{% url 'ciphers:index' %}">Back to list of Caesars</a>

ciphers/templates/ciphers/index.html
<h1>All Ciphers</h1>
{% if caesars %}
    <h2>Caesar Ciphers</h2>
    <ul>
    {% for caesar in caesars %}
        <li><a href="/ciphers/caesar/{{ caesar.id }}/">{{ caesar.caesar_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No ciphers are available.</p>
{% endif %}

{% if atbashs %}
    <h2>Atbash Ciphers</h2>
    <ul>
    {% for atbash in atbashs %}
        <li><a href="/ciphers/atbash/{{ atbash.id }}/">{{ atbash.atbash_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No ciphers are available.</p>
{% endif %}

{% if alphanumerics %}
    <h2>Alphanumeric Ciphers</h2>
    <ul>
    {% for alphanumeric in alphanumerics %}
        <li><a href="/ciphers/alphanumeric/{{ alphanumeric.id }}/">{{ alphanumeric.alphanumeric_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No ciphers are available.</p>
{% endif %}

{% if vigeneres %}
    <h2>Vigenere Ciphers</h2>
    <ul>
    {% for vigenere in vigeneres %}
        <li><a href="/ciphers/vigenere/{{ vigenere.id }}/">{{ vigenere.vigenere_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No ciphers are available.</p>
{% endif %}

<li><a href="/ciphers/create/">Create a New Caesar Cipher</a></li>

ciphers/templates/ciphers/show.html
<h2>Caesar Message</h2>
  {{ caesar }}

  {# { caesar.decode(3) } #}


<a href="{% url 'ciphers:update' caesar.id %}">Update Caesar</a><br><br>
<a href="{% url 'ciphers:delete' caesar.id %}">Delete Caesar</a><br><br>

<a href="{% url 'ciphers:index' %}">Back to list of Caesars</a>